-- <ChangeSet id="create schema" delimiter=";" />

CREATE SCHEMA IF NOT EXISTS HRDB;

CREATE TABLE IF NOT EXISTS HRDB.USERS
(
  USERID      INT NOT NULL,
  USERNAME    VARCHAR2(50),
  RATE        NUMBER(12, 2),
  CREATE_TIME DATE DEFAULT sysdate,
  CONSTRAINT PK_USERID PRIMARY KEY (USERID)
);

-- <ChangeSet id="load seed data" delimiter=";" />

INSERT INTO HRDB.USERS (USERID, USERNAME) VALUES (1, 'Aiden');
INSERT INTO HRDB.USERS (USERID, USERNAME) VALUES (2, 'Ethan');
INSERT INTO HRDB.USERS (USERID, USERNAME) VALUES (3, 'Liam');
INSERT INTO HRDB.USERS (USERID, USERNAME) VALUES (4, 'Noah');
INSERT INTO HRDB.USERS (USERID, USERNAME) VALUES (5, 'Jacob');
INSERT INTO HRDB.USERS (USERID, USERNAME) VALUES (6, 'Benjamin');
INSERT INTO HRDB.USERS (USERID, USERNAME) VALUES (7, 'Senthil');
